-- 1. Create the application table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

-- 2. Ensure 'sa' has the correct password for Spring to connect
-- This MUST match your application.properties spring.datasource.password

-- 3. Set a base permission that allows new users to see the PUBLIC schema
-- This prevents the "Schema PUBLIC not found" error after a user logs in
GRANT ALTER ANY SCHEMA TO sa;